# Generated by Django 3.2.13 on 2022-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0002_auto_20220824_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengali',
            name='spclnks',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
