# Generated by Django 3.2.13 on 2022-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0003_bengali_spclnks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengali',
            name='poster',
            field=models.ImageField(blank=True, upload_to='poster/'),
        ),
    ]
