# Generated by Django 3.2.13 on 2022-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0005_alter_bengali_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengali',
            name='watch',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
