# Generated by Django 3.2.13 on 2022-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0006_bengali_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bengali',
            name='poster',
            field=models.ImageField(upload_to='poster/bengali/'),
        ),
    ]
