# Generated by Django 3.2.13 on 2022-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0007_alter_bengali_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengali',
            name='embededlink',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
