# Generated by Django 3.2.13 on 2022-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0008_bengali_embededlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bengali',
            name='about',
            field=models.CharField(default='No About Updated', max_length=200),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='embededlink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='hero',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='heroine',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='lang',
            field=models.CharField(default='Bengali', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='poster',
            field=models.ImageField(default='', upload_to='poster/bengali/'),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='price',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='quality',
            field=models.CharField(default='HD 1080', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='spclnks',
            field=models.CharField(blank=True, default='#', max_length=40),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='types',
            field=models.CharField(default='Web Series', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='watch',
            field=models.CharField(blank=True, default='bengcinema/bengwebseries', max_length=20),
        ),
    ]
