# Generated by Django 3.2.13 on 2022-08-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0010_bengcinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengcinema',
            name='ribbon',
            field=models.CharField(default='<div class="ribbon-featured">New Release</div>', max_length=80),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='poster',
            field=models.ImageField(default='', upload_to='poster/bengali/cinema/'),
        ),
    ]
