# Generated by Django 3.2.13 on 2022-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0012_bengwebseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bengali',
            name='poster',
            field=models.ImageField(default='', upload_to='poster/bengali/all/'),
        ),
    ]
