# Generated by Django 3.2.13 on 2022-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0013_alter_bengali_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengali',
            name='ribbon',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='ribbon',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengwebseries',
            name='hero',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengwebseries',
            name='heroine',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengwebseries',
            name='ribbon',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
    ]
