# Generated by Django 3.2.13 on 2022-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengali', '0014_auto_20220828_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bengali',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='embededlink',
            field=models.CharField(blank=True, default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengali',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='embededlink',
            field=models.CharField(blank=True, default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengcinema',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bengwebseries',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bengwebseries',
            name='embededlink',
            field=models.CharField(blank=True, default='#', max_length=500),
        ),
    ]
