# Generated by Django 3.2.13 on 2022-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('repname', models.CharField(max_length=50)),
                ('repemail', models.EmailField(max_length=100)),
                ('repissue', models.TextField(max_length=50)),
                ('replink', models.CharField(max_length=50)),
                ('repmessage', models.TextField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
