# Generated by Django 3.2.13 on 2022-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('priemail', models.EmailField(max_length=100)),
                ('extemail', models.EmailField(max_length=100)),
                ('jobdesc', models.TextField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
