# Generated by Django 3.2.13 on 2022-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20220826_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='Cinema', max_length=20)),
                ('ribbon', models.CharField(default='<div class="ribbon-featured">New Release</div>', max_length=80)),
                ('name', models.CharField(default='', max_length=40)),
                ('lang', models.CharField(default='Bengali', max_length=20)),
                ('poster', models.ImageField(default='', upload_to='poster/english/cinema/')),
                ('quality', models.CharField(default='HD 1080', max_length=20)),
                ('spclnks', models.CharField(blank=True, default='#', max_length=40)),
                ('price', models.CharField(default='Free', max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('hero', models.CharField(default='', max_length=20)),
                ('heroine', models.CharField(default='', max_length=20)),
                ('about', models.CharField(default='No About Updated', max_length=200)),
                ('watch', models.CharField(blank=True, default='engcinema', max_length=20)),
                ('embededlink', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EngWebseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='WebSeries', max_length=20)),
                ('ribbon', models.CharField(default='<div class="ribbon-featured">New Release</div>', max_length=80)),
                ('name', models.CharField(default='', max_length=40)),
                ('lang', models.CharField(default='English', max_length=20)),
                ('poster', models.ImageField(default='', upload_to='poster/english/webseries/')),
                ('quality', models.CharField(default='HD 1080', max_length=20)),
                ('spclnks', models.CharField(blank=True, default='#', max_length=40)),
                ('price', models.CharField(default='Free', max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('hero', models.CharField(default='', max_length=20)),
                ('heroine', models.CharField(default='', max_length=20)),
                ('about', models.CharField(default='No About Updated', max_length=200)),
                ('watch', models.CharField(blank=True, default='engwebseries', max_length=20)),
                ('embededlink', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='english',
            name='poster',
            field=models.ImageField(default='', upload_to='poster/english/all/'),
        ),
    ]
