# Generated by Django 3.2.13 on 2022-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220826_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='ribbon',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
    ]
