# Generated by Django 3.2.13 on 2022-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_ribbon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='embededlink',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
