# Generated by Django 3.2.13 on 2022-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_spclnks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about',
            field=models.CharField(blank=True, default='Nothing Updated Yet', max_length=200),
        ),
    ]
