# Generated by Django 3.2.13 on 2022-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindi',
            name='embededlink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='about',
            field=models.CharField(default='No About Updated', max_length=200),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='hero',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='heroine',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='lang',
            field=models.CharField(default='Hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='poster',
            field=models.ImageField(default='', upload_to='poster/hindi/'),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='price',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='quality',
            field=models.CharField(default='4K', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='spclnks',
            field=models.CharField(blank=True, default='#', max_length=40),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='types',
            field=models.CharField(default='Web Series', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='watch',
            field=models.CharField(blank=True, default='hincinema/hinwebseries', max_length=20),
        ),
    ]
