# Generated by Django 3.2.13 on 2022-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0004_auto_20220828_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hincinema',
            name='embededlink',
            field=models.CharField(blank='True', default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='hincinema',
            name='lang',
            field=models.CharField(default='Hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='hincinema',
            name='watch',
            field=models.CharField(blank=True, default='hincinema', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='embededlink',
            field=models.CharField(blank='True', default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='embededlink',
            field=models.CharField(blank='True', default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='lang',
            field=models.CharField(default='Hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='watch',
            field=models.CharField(blank=True, default='hinwebseries', max_length=20),
        ),
    ]
