# Generated by Django 3.2.13 on 2022-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0005_auto_20220828_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hincinema',
            name='spclnks',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='hindi',
            name='spclnks',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='spclnks',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
