# Generated by Django 3.2.13 on 2022-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindi', '0007_auto_20220831_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hincinema',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hincinema',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='hero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hinwebseries',
            name='heroine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
