# Generated by Django 3.2.13 on 2022-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requestmovie',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('reqname', models.CharField(max_length=50)),
                ('reqemail', models.EmailField(max_length=100)),
                ('reqmovie', models.TextField(max_length=50)),
                ('filmname', models.CharField(max_length=50)),
                ('explnmovie', models.TextField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
